docker run --rm -d -p 3306:3306 --name mysql --volume ~/Desktop/db/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root mysql

sleep 5
while ! docker exec mysql mysqladmin -u root -proot ping --silent; do
    echo "Waiting for MySQL to be ready..."
    sleep 2
done


docker exec mysql mysql -u root -proot -e 'create database supertokens;'
docker exec mysql mysql -u root -proot -e 'create database st0;'
docker exec mysql mysql -u root -proot -e 'create database st1;'
docker exec mysql mysql -u root -proot -e 'create database st2;'
docker exec mysql mysql -u root -proot -e 'create database st3;'
docker exec mysql mysql -u root -proot -e 'create database st4;'
docker exec mysql mysql -u root -proot -e 'create database st5;'
docker exec mysql mysql -u root -proot -e 'create database st6;'
docker exec mysql mysql -u root -proot -e 'create database st7;'
docker exec mysql mysql -u root -proot -e 'create database st8;'
docker exec mysql mysql -u root -proot -e 'create database st9;'
docker exec mysql mysql -u root -proot -e 'create database st10;'
docker exec mysql mysql -u root -proot -e 'create database st11;'
docker exec mysql mysql -u root -proot -e 'create database st12;'
docker exec mysql mysql -u root -proot -e 'create database st13;'
docker exec mysql mysql -u root -proot -e 'create database st14;'
docker exec mysql mysql -u root -proot -e 'create database st15;'
docker exec mysql mysql -u root -proot -e 'create database st16;'
docker exec mysql mysql -u root -proot -e 'create database st17;'
docker exec mysql mysql -u root -proot -e 'create database st18;'
docker exec mysql mysql -u root -proot -e 'create database st19;'
docker exec mysql mysql -u root -proot -e 'create database st20;'
docker exec mysql mysql -u root -proot -e 'create database st21;'
docker exec mysql mysql -u root -proot -e 'create database st22;'
docker exec mysql mysql -u root -proot -e 'create database st23;'
docker exec mysql mysql -u root -proot -e 'create database st24;'
docker exec mysql mysql -u root -proot -e 'create database st25;'
docker exec mysql mysql -u root -proot -e 'create database st26;'
docker exec mysql mysql -u root -proot -e 'create database st27;'
docker exec mysql mysql -u root -proot -e 'create database st28;'
docker exec mysql mysql -u root -proot -e 'create database st29;'
docker exec mysql mysql -u root -proot -e 'create database st30;'
docker exec mysql mysql -u root -proot -e 'create database st31;'
docker exec mysql mysql -u root -proot -e 'create database st32;'
docker exec mysql mysql -u root -proot -e 'create database st33;'
docker exec mysql mysql -u root -proot -e 'create database st34;'
docker exec mysql mysql -u root -proot -e 'create database st35;'
docker exec mysql mysql -u root -proot -e 'create database st36;'
docker exec mysql mysql -u root -proot -e 'create database st37;'
docker exec mysql mysql -u root -proot -e 'create database st38;'
docker exec mysql mysql -u root -proot -e 'create database st39;'
docker exec mysql mysql -u root -proot -e 'create database st40;'
docker exec mysql mysql -u root -proot -e 'create database st41;'
docker exec mysql mysql -u root -proot -e 'create database st42;'
docker exec mysql mysql -u root -proot -e 'create database st43;'
docker exec mysql mysql -u root -proot -e 'create database st44;'
docker exec mysql mysql -u root -proot -e 'create database st45;'
docker exec mysql mysql -u root -proot -e 'create database st46;'
docker exec mysql mysql -u root -proot -e 'create database st47;'
docker exec mysql mysql -u root -proot -e 'create database st48;'
docker exec mysql mysql -u root -proot -e 'create database st49;'
docker exec mysql mysql -u root -proot -e 'create database st50;'
